config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

  resources :registered_applications,
            only: [:index, :show, :new, :create, :destroy],
            as: :applications

  devise_for :users

  get '/about', to: 'welcome#about'

  root 'welcome#index'

end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :user
  has_many :events

  validates_presence_of :name, message: "can't be blank!"
  validates_uniqueness_of :name, scope: :user_id, message: "is already in use (by you!)"
  validates_presence_of :url, message: "can't be blank!"
  validates_uniqueness_of :url, message: "already belongs to another application"
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :application
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :applications
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable

end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!

  before_action :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    application = Application.find_by(url: request.env['HTTP_ORIGIN'])

    if application
      @event = application.events.build(event_params)

      if @event.save
        render json: @event, status: :created
      else
        render json: @event.errors, status: :unprocessable_entity
      end
    else
      render json: "Unregistered application", status: :unprocessable_entity
    end
  end

  def preflight
    head 200
  end



  private

  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/api/v1/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    application = Application.find_by(url: request.env['HTTP_ORIGIN'])

    if application
      @event = application.events.build(event_params)

      if @event.save
        render json: @event, status: :created
      else
        render json: @event.errors, status: :unprocessable_entity
      end
    else
      render json: "Unregistered application", status: :unprocessable_entity
    end
  end



  private

  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def after_sign_in_path_for(user)
    applications_path
  end
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def index
    @applications = current_user.applications
  end

  def show
    begin
      @application = current_user.applications.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @application = nil
    end

    if @application
      @event_counts = @application.events.group(:name).count
    end
  end

  def new
    @application = Application.new
  end

  def create
    @application = current_user.applications.build(application_params)

    if @application.save
      flash[:notice] = "Your new application has been registered."
      redirect_to applications_path
    else
      flash[:error] = "There was an error registering your application. Please try again."
      render :new
    end
  end

  def destroy
    @application = current_user.applications.find(params[:id])

    if @application.destroy
      flash[:notice] = "Application deleted successfully."
      redirect_to applications_path
    else
      flash[:error] = "There was an error deleting the application. Please try again."
      render :show
    end
  end


  private

  def application_params
    params.require(:application).permit(:name, :url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    class_text = errors.any? ? 'form-group has-error' : 'form-group'
    content_tag :div, capture(&block), class: class_text
  end
end

app/helpers/event_helper.rb
module EventHelper
  # The colors used by Google Charts
  # The last color is placed at index 0
  # to allow for "modulo wrapping"
  COLORS = ['#743411', '#3366CC', '#DC3912', '#FF9900',
            '#109618', '#990099', '#0099C6', '#DD4477',
            '#66AA00', '#B82E2E', '#316395', '#994499',
            '#22AA99', '#AAAA11', '#6633CC', '#E67300',
            '#8B0707', '#651067', '#329262', '#5574a6',
            '#3b3eac', '#b77322', '#16d620', '#b91383',
            '#f4359e', '#9c5935', '#a9c413', '#2a778d',
            '#668d1c', '#bea413', '#0c5922']

  HIGHEST_COLOR_VALUE = COLORS.length

  def select_color(index=rand(1..COLORS.length))
    COLORS[index % HIGHEST_COLOR_VALUE]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title ||= "DoTell" %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- include Google Charts -->
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Registered Applications", applications_path %></li>
    </ul>

    <div class="container">
      <% if user_signed_in? %>
        Signed in as: <strong><%= current_user.email %></strong> |
        <%= link_to "Edit Profile", edit_user_registration_path, class: 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'navbar-link' %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, class: 'navbar-link' %> -
        <%= link_to "Sign In", new_user_session_path, class: 'navbar-link' %>
      <% end %>
    </div>

    <div class="flash">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>

    <%= yield %>
  </div>

</body>
</html>

app/views/registered_applications/_application.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to application.name, application_path(application) %> <span class='very-small'>(<%= application.url %>)</span>
    </h4>
  </div>
</div>

app/views/registered_applications/_event_display.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="media">
      <table id="event-list">
        <tr>
          <th>Event</th>
          <th>Count</th>
        </tr>
        <% event_counts.each_with_index do |(event_name, count), i| %>
          <tr style="background-color:<%= select_color(i + 1) %>" >
            <td><%= event_name %></td>
            <td><%= count %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="col-md-5">
    <%= pie_chart event_counts %>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <%= line_chart @application.events.group_by_day(:created_at).count %>
  </div>
</div>

app/views/registered_applications/_form.html.erb
<%= form_for application do |f| %>
  <% if application.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(application.errors.count, "error") %>.</h4>
      <ul>
        <% application.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(application.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Enter the name of your application' %>
  <% end %>
  <%= form_group_tag(application.errors[:url]) do %>
    <%= f.label :url %>
    <%= f.url_field :url, class: 'form-control', placeholder: 'https://my_app.example.com' %>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/registered_applications/index.html.erb
<% @page_title = "Registered Applications" %>
<h2>Index Page</h2>

<% if @applications.empty? %>
  <p>You have not registered any applications yet.</p>
<% else %>
  <% @applications.each do |application| %>
    <%= render partial: 'registered_applications/application', locals: { application: application } %>
  <% end %>
<% end %>

<%= link_to "New Application", new_application_path, class: "btn btn-success" %>

app/views/registered_applications/new.html.erb
<% @page_title = "New Application" %>

<%= render partial: 'registered_applications/form', locals: { application: @application } %>

app/views/registered_applications/show.html.erb
<% if !@application %>
  <h1>This Application does not exist, or you do not have permission to view it.</h1>
<% else %>
  <% @page_title = "#{@application.name} - DoTell" %>
  <h1><%= @application.name %></h1>
  <p><%= @application.url %></p>
  <br>
  <% if @event_counts.any? %>
    <%= render partial: 'event_display', locals: { event_counts: @event_counts } %>
  <% else %>
    <h3>This application has no events associated with it.</h3>
  <% end %>

  <!-- additional content will go here... -->

  <%= link_to "Delete Registered Application", application_path(@application), class: 'btn btn-danger', method: :delete, data: { confirm: "Are you sure you want to permanently delete this application?" } %>
<% end %>

app/views/registered_applications/update.html.erb
<h1>RegisteredApplications#update</h1>
<p>Find me in app/views/registered_applications/update.html.erb</p>

app/views/welcome/about.html.erb
<h1>DoTell</h1>
<p>created by Jeff Minnear</p>

app/views/welcome/index.html.erb
<h1>DoTell</h1>
<p>An analytics service and reporting tool to track events on websites</p>
<br>
<div id="home-carousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#home-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#home-carousel" data-slide-to="1"></li>
    <li data-target="#home-carousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="https://raw.githubusercontent.com/jeffminnear/do-tell/change-home/app/assets/images/dt-1.png">
    </div>

    <div class="item">
      <img src="https://raw.githubusercontent.com/jeffminnear/do-tell/change-home/app/assets/images/dt-2.png">
    </div>

    <div class="item">
      <img src="https://raw.githubusercontent.com/jeffminnear/do-tell/change-home/app/assets/images/dt-3.png">
    </div>
  </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#home-carousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#home-carousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>